# Custom Language File for Launcher Customizer

[ejs.app]
title = "Arkalia Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Sankah23/Arkalia"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/fFBTTfpQNZ"

[ejs.settings]
sourceGithubLink = "https://github.com/Sankah23/Arkalia"
supportLink = "https://github.com/Sankah23/Arkalia/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR ARKALIA"
welcomeDescription = "La Cité vous protège. Du moins, c’est ce qu’ils disent. À l’extérieur, la pluie est mortelle, les infectés rôdent, et les pillards guettent. Pourtant, certains survivants affirment que la vérité est ailleurs. Pourquoi des citoyens disparaissent-ils sans laisser de traces ? Que cache la Milice sous la ville ? Rebelles ou obéissants, chacun devra choisir son camp. Mais une chose est sûre : la Cité ...."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics d'Arkalia."
